uglifyjs.cmd js/platform.js > uglify/platform.min.js
uglifyjs.cmd js/ios_fullscreen.js > uglify/ios_fullscreen.min.js
uglifyjs.cmd js/ctl_utils.js > uglify/ctl_utils.min.js
uglifyjs.cmd js/sprite_lib.js > uglify/sprite_lib.min.js
uglifyjs.cmd js/settings.js > uglify/settings.min.js
uglifyjs.cmd js/CGameSettings.js > uglify/CGameSettings.min.js
uglifyjs.cmd js/CLang.js > uglify/CLang.min.js
uglifyjs.cmd js/CPreloader.js > uglify/CPreloader.min.js
uglifyjs.cmd js/CMain.js > uglify/CMain.min.js
uglifyjs.cmd js/CTextButton.js > uglify/CTextButton.min.js
uglifyjs.cmd js/CToggle.js > uglify/CToggle.min.js
uglifyjs.cmd js/CGfxButton.js > uglify/CGfxButton.min.js
uglifyjs.cmd js/CMenu.js > uglify/CMenu.min.js
uglifyjs.cmd js/CGame.js > uglify/CGame.min.js
uglifyjs.cmd js/CInterface.js > uglify/CInterface.min.js
uglifyjs.cmd js/CCreditsPanel.js > uglify/CCreditsPanel.min.js
uglifyjs.cmd js/CBetPanel.js > uglify/CBetPanel.min.js
uglifyjs.cmd js/CChipPanel.js > uglify/CChipPanel.min.js
uglifyjs.cmd js/CSimpleBetPanel.js > uglify/CSimpleBetPanel.min.js
uglifyjs.cmd js/CForecastPanel.js > uglify/CForecastPanel.min.js
uglifyjs.cmd js/CBetList.js > uglify/CBetList.min.js
uglifyjs.cmd js/CFichesController.js > uglify/CFichesController.min.js
uglifyjs.cmd js/CButBet.js > uglify/CButBet.min.js
uglifyjs.cmd js/CVector2.js > uglify/CVector2.min.js
uglifyjs.cmd js/CMsgBox.js > uglify/CMsgBox.min.js
uglifyjs.cmd js/CTrackBg.js > uglify/CTrackBg.min.js
uglifyjs.cmd js/CGreyhound.js > uglify/CGreyhound.min.js
uglifyjs.cmd js/CTweenController.js > uglify/CTweenController.min.js
uglifyjs.cmd js/CRankingGui.js > uglify/CRankingGui.min.js
uglifyjs.cmd js/CArrivalPanel.js > uglify/CArrivalPanel.min.js
uglifyjs.cmd js/CWinPanel.js > uglify/CWinPanel.min.js
uglifyjs.cmd js/CLosePanel.js > uglify/CLosePanel.min.js
uglifyjs.cmd js/CButStartRace.js > uglify/CButStartRace.min.js
uglifyjs.cmd js/CAreYouSurePanel.js > uglify/CAreYouSurePanel.min.js
uglifyjs.cmd js/CCTLText.js > uglify/CCTLText.min.js
uglifyjs.cmd js/CFicheBut.js > uglify/CFicheBut.min.js